name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: pip install -r dev-requirements.txt
    - name: Run black
      run: which black && black --check crab/ setup.py || true
    - name: Try installing the package
      run: pip install -e .
    - name: Try running crab
      run: crab --version
